workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'  # Executa o pipeline apenas na branch main
    - if: '$CI_COMMIT_BRANCH == "qa"' # Executa o pipeline apenas na branch qa

variables:
  VERSION: "2.0"

stages:
  - build
  - deploy

build_frontend:
  stage: build
  tags:
    - oci
  script:
    - docker build -t vsantosmt/portfolio-frontend:$VERSION ./frontend

build_backend:
  stage: build
  tags:
    - oci
  needs:
    - build_frontend
  script:
    - docker build -t vsantosmt/portfolio-backend:$VERSION ./backend
    - docker build -t vsantosmt/portfolio-easypanel:$VERSION .

push_image:
  stage: build
  tags:
    - oci
  needs:
    - build_frontend
    - build_backend
  script:
    - docker push vsantosmt/portfolio-frontend:$VERSION
    - docker push vsantosmt/portfolio-backend:$VERSION
      
execute_container:
  stage: deploy
  tags:
    - oci
  needs:
    - push_image
  before_script:
     - |
          CONTAINERS_RUNNING=$(docker ps -q)

          if [ -n "$CONTAINERS_RUNNING" ]; then
            echo "Containers em execução encontrados. Removendo containers..."
            docker stop $CONTAINERS_RUNNING
            docker rm -f $CONTAINERS_RUNNING
          else
            echo "Nenhum container em execução encontrado. Pulando remoção..."
          fi
  script:
    - docker run -dti --name webserver-frontend -p 5173:80 vsantosmt/portfolio-frontend:$VERSION
    - docker run -dti --name webserver-backend -p 5000:5000 vsantosmt/portfolio-backend:$VERSION
    - docker run -dti --name webserver-backend-easypanel -p 5174:5173 -p 5002:5000 vsantosmt/portfolio-easypanel:$VERSION #

