workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "qa"'  # Executa o pipeline apenas na branch main e qa

variables:
  VERSION: "1.0"

stages:
  - build
  - deploy

create_image:
  stage: build
  tags:
    - oci
  script:
    - docker build -t vsantosmt/portfolio:$VERSION app/.
    - docker push vsantosmt/portfolio:$VERSION

execute_image:
  stage: deploy
  tags:
    - oci
  needs:
    - create_image
  before_script:
    - docker rm -f $(docker ps -aq) #remove containers ativos
  script:
    - docker run -dti --name webserver -p 80:80 vsantosmt/portfolio:$VERSION
  