trigger:
  branches:
    include:
      - main

variables: 
  VERSION: "2.0"

pool:
  name: "Linux-GCP"

stages:
  - stage: build
    jobs:
      - job: clone_repo
        displayName: clone_repo
        steps:
        - script:
            git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
          displayName: 'Cloning GitLab repository'
          env:
            GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

  - stage: build
    jobs:
      - job: build_frontend
        displayName: build_frontend
        steps:
        - script: docker build -t vsantosmt/portfolio-frontend:$VERSION ./frontend
          displayName: builded frontend
  - stage: build
    jobs:
      - job: push_frontend
        displayName: push_frontend
        steps:
          - script: docker push vsantosmt/portfolio-frontend:$VERSION
            displayName: pushed frontend

# steps:
# - script:
#     git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
#   displayName: 'Cloning GitLab repository'
#   env:
#     GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

# - script:
#     docker build -t vsantosmt/portfolio-frontend:$VERSION ./frontend
#   displayName: 'Builded frontend'

# - script:
#     docker build -t vsantosmt/portfolio-backend:$VERSION ./backend
#   displayName: 'Builded backend'

# - script:
#     docker build -t vsantosmt/portfolio-nginx:$VERSION ./nginx
#   displayName: 'Builded NGINX'