trigger:
  branches:
    include:
      - main

variables: 
  VERSION: "2.0"

pool:
  name: "Linux-GCP"

stages:
  - stage: build
    jobs:
      - job: clone_repo
        displayName: clone_repo
        steps:
        - script:
            git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
          displayName: 'Cloning GitLab repository'
          env:
            GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

      - job: logindocker_pushdockerhub
        displayName: login_docker
        steps:
          #login docker hub
          - task: Docker@2
            displayName: 'Login to Docker Hub'
            inputs:
              command: 'login'
              containerRegistry: 'DockerHubConnection'
          
          #build do frontend
          - task: Docker@2
            displayName: build_frontend
            inputs:
              command: build
              Dockerfile: frontend/Dockerfile
              tags: $(DOCKER_USERNAME)/portfolio-frontend:$(VERSION)

          #push do frontend
          - task: Docker@2
            displayName: push_frontend
            inputs:
              command: push
              repository: $(DOCKER_USERNAME)/portofio-frontend
              tags: $(VERSION)


