trigger:
  branches:
    include:
      - main

pool:
  vmImage: "Linux-GCP"

steps:
- script: |
    git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
  displayName: 'Cloning GitLab repository'
  env:
    GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

    