trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    git clone https://gitlab.com/santos.viniciusmt/portfolio.git
    echo 'Cloned'
  displayName: 'Cloning GitLab repository'
