trigger:
  branches:
    include:
      - main

variables: 
  VERSION: "2.0"

pool:
  name: "Linux-GCP"

stages:
  - stage: build
    jobs:
      - job: clone_build_push_frontend
        displayName: clone_build_push_frontend
        steps:
        - script:
            git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
          displayName: 'Cloning GitLab repository'
          env:
            GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

        - script: docker build -t vsantosmt/portfolio-frontend:$VERSION ./frontend
          displayName: builded frontend

        - script: docker push vsantosmt/portfolio-frontend:$VERSION
          displayName: pushed frontend