trigger:
  branches:
    include:
      - main

variables:
- group: TOKENS

pool:
  name: "Linux-GCP"

stages:
  - stage: build
    jobs:
      - job: clone_repo
        displayName: clone_repo
        steps:
        - script:
            git clone https://santos.viniciusmt:$(GITLAB_ACCESS_TOKEN)@gitlab.com/santos.viniciusmt/portfolio.git
          displayName: 'Cloning GitLab repository'
          env:
            GITLAB_ACCESS_TOKEN: $(GITLAB_ACCESS_TOKEN)

      - job: build_push_frontend
        displayName: build_push_frontend
        steps: 
        - script: |
            echo $(DOCKER_PASSWORD) | docker login --username $(DOCKER_USERNAME) --password-stdin
            docker build -t $(DOCKER_USERNAME)/portfolio-frontend:2.0 frontend/
            docker push $(DOCKER_USERNAME)/portfolio-frontend:2.0
          displayName: 'Build and Push Docker Image'

  - stage: deploy
    jobs:
      - job: execute_frontend
        displayName: execute_frontend
        steps:
          - script: docker run -dti --name webserver-frontend -p 5173:80 vsantosmt/portfolio-frontend:2.0

    