version: '3'

services:
  # Serviço do Backend (Flask)
  backend:
    build:
      context: ./backend  # Pasta onde está o Dockerfile do Flask
      dockerfile: Dockerfile
    container_name: webserver-backend
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do host para a porta 5000 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"  # Roteamento de tráfego para /api
      - "traefik.http.services.backend.loadbalancer.server.port=5000"

  # Serviço do Frontend (Vite)
  frontend:
    build:
      context: ./frontend  # Pasta onde está o Dockerfile do Vite
      dockerfile: Dockerfile
    container_name: webserver-frontend
    ports:
      - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`vgsenterprise.online`) && PathPrefix(`/`)"  # Roteamento de tráfego para frontend

  # Serviço do Traefik
  traefik:
    image: traefik:v2.10
    container_name: webserver-traefik
    command:
      - "--api.insecure=true"  # Habilita a UI do Traefik na porta 8080
      - "--providers.docker=true"  # Habilita o provedor Docker
      - "--entrypoints.web.address=:80"  # Entrypoint para tráfego HTTP
      - "--entrypoints.websecure.address=:443"  # Entrypoint para tráfego HTTPS
    ports:
      - "80:80"   # Porta HTTP
      - "443:443" # Porta HTTPS
      - "8080:8080" # Porta da UI do Traefik
    networks:
      - proxy
    labels:
      - "traefik.enable=true"

networks:
  proxy:
    name: proxy
