version: '3'

services:
  # Serviço do Backend (Flask)
  backend:
    build:
      context: ./backend  # Pasta onde está o Dockerfile do Flask
      dockerfile: Dockerfile
    container_name: webserver-backend
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do host para a porta 5000 do contêiner
    networks:
      - proxy

  # Serviço do Frontend (Vite)
  frontend:
    build:
      context: ./frontend  # Pasta onde está o Dockerfile do Vite
      dockerfile: Dockerfile
    container_name: webserver-frontend
    ports:
      - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner
    networks:
      - proxy

  # Serviço do Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver-nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html  # Diretório do frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Configuração personalizada do Nginx
      # - ./data/certbot/conf:/etc/letsencrypt  # Volume para os certificados
      # - ./data/certbot/www:/var/www/certbot  # Diretório para validação do Certbot
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - proxy

  # Serviço do Certbot
  # certbot:
  #   build:
  #     context: ./certbot
  #     dockerfile: Dockerfile
  #   container_name: webserver-certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done;'"
  #   networks:
  #     - proxy
  #   depends_on:
  #     - nginx

networks:
  proxy:
    name: proxy