version: '3'

services:
  # Serviço do Backend (Flask)
  backend:
    build:
      context: ./backend  # Pasta onde está o Dockerfile do Flask
      dockerfile: Dockerfile
    container_name: webserver-backend
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do host para a porta 5000 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver-backend.rule=Host(`api.vgsenterprise.online`)"  # Substitua pelo seu subdomínio
      - "traefik.http.routers.webserver-backend.entrypoints=websecure"
      - "traefik.http.routers.webserver-backend.tls=true"
      - "traefik.http.routers.webserver-backend.tls.certresolver=ewacademy-cert"
      - "traefik.http.services.webserver-backend.loadbalancer.server.port=5000"  # Porta do backend

  # Serviço do Frontend (Vite)
  frontend:
    build:
      context: ./frontend  # Pasta onde está o Dockerfile do Vite
      dockerfile: Dockerfile
    container_name: webserver-frontend
    ports:
      - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver-frontend.rule=Host(`vgsenterprise.online`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.webserver-frontend.entrypoints=websecure"
      - "traefik.http.routers.webserver-frontend.tls=true"
      - "traefik.http.routers.webserver-frontend.tls.certresolver=ewacademy-cert"
      - "traefik.http.services.webserver-frontend.loadbalancer.server.port=5173"  # Porta do frontend

  # Serviço do Traefik
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.ewacademy-cert.acme.tlschallenge=true"
      - "--certificatesresolvers.ewacademy-cert.acme.email=santos.viniciusmt@gmail.com"
      - "--certificatesresolvers.ewacademy-cert.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
