version: '3'

services:
  # Serviço do Backend (Flask)
  backend:
    build:
      context: ./backend  # Pasta onde está o Dockerfile do Flask
      dockerfile: Dockerfile
    container_name: webserver-backend
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do host para a porta 5000 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver-backend.rule=Host(`api.vgsenterprise.online`)"  # Substitua pelo seu subdomínio
      - "traefik.http.routers.webserver-backend.entrypoints=https"
      - "traefik.http.routers.webserver-backend.tls=true"
      - "traefik.http.routers.webserver-backend.tls.certresolver=myresolver"

  # Serviço do Frontend (Vite)
  frontend:
    build:
      context: ./frontend  # Pasta onde está o Dockerfile do Vite
      dockerfile: Dockerfile
    container_name: webserver-frontend
    ports:
      - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver-frontend.rule=Host(`vgsenterprise.online`)"  # Substitua pelo seu domínio
      - "traefik.http.routers.webserver-frontend.entrypoints=https"
      - "traefik.http.routers.webserver-frontend.tls=true"
      - "traefik.http.routers.webserver-frontend.tls.certresolver=myresolver"

  # Serviço do Traefik
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.myresolver.acme.email=santos.viniciusmt@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-cert-storage:/letsencrypt"
    
    networks:
      - proxy

networks:
  proxy:
    name: proxy
