version: '3'

services:
  # Serviço do Backend (Flask)
  backend:
    build:
      context: ./backend  # Pasta onde está o Dockerfile do Flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeando a porta 5000 do host para a porta 5000 do contêiner
    networks:
      - proxy

  # Serviço do Frontend (Vite)
  frontend:
    build:
      context: ./frontend  # Pasta onde está o Dockerfile do Vite
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner
    networks:
      - proxy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - proxy

  # Serviço EasyPanel
  # easypanel:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   environment:
  #     - BACKEND_URL=http://backend:5000  # Variável de ambiente apontando para o backend Python
  #     - FRONTEND_URL=http://frontend:80  # Variável de ambiente apontando para o frontend
  #   ports:
  #     - "5174:5173"  # EasyPanel estará acessível na porta 5174
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend
  #     - frontend

# networks:
#   app-network:
#     driver: bridge


# old
# services:
#   # Serviço do Backend (Flask)
#   backend:
#     build:
#       context: ./backend  # Pasta onde está o Dockerfile do Flask
#       dockerfile: Dockerfile
#     # ports:
#     #   - "5000:5000"
#     environment:
#       - VIRTUAL_HOST=vgsenterprise.online
#       - VIRTUAL_PORT=5000
#       - LETSENCRYPT_HOST=vgsenterprise.online
#       - LETSENCRYPT_EMAIL=santos.viniciusmt@gmail.com
#     networks:
#       - proxy

#   # Serviço do Frontend (Vite)
#   frontend:
#     build:
#       context: ./frontend  # Pasta onde está o Dockerfile do Vite
#       dockerfile: Dockerfile
#     # ports:
#     #   - "5173:80"  # Mapeando a porta 5173 do host para a porta 80 do contêiner.
#     environment:
#       - VIRTUAL_HOST=vgsenterprise.online
#       - VIRTUAL_PORT=5173
#       - LETSENCRYPT_HOST=vgsenterprise.online
#       - LETSENCRYPT_EMAIL=santos.viniciusmt@gmail.com
#     networks:
#       - proxy

#   # Serviço Nginx como Proxy Reverso
#   nginx-proxy:
#     container_name: nginx-proxy
#     image: nginxproxy/nginx-proxy
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - ./certs:/etc/nginx/certs
#       - ./vhost:/etc/nginx/vhost.d
#       - ./html:/usr/share/nginx/html
#     networks:
#       - proxy
#     privileged: true

#   # Serviço Let's Encrypt
#   letsencrypt:
#     container_name: letsencrypt
#     image: nginxproxy/acme-companion
#     restart: always
#     volumes_from:
#       - nginx-proxy
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#     networks:
#       - proxy

networks:
  proxy:
    name: proxy

