version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webserver-backend
    ports:
      - "5000:5000"
    networks:
      - proxy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webserver-frontend
    ports:
      - "5173:5173"
    networks:
      - proxy
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: webserver-nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  proxy:
    name: proxy
