# Use a imagem base do Nginx
FROM nginx:alpine

# Copie a configuração personalizada do Nginx para o container
COPY nginx.conf /etc/nginx/nginx.conf

# Exponha as portas que o Nginx vai usar
EXPOSE 80 443
