apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # A porta externa (do host)
      targetPort: 5000    # A porta interna do container
  type: ClusterIP   # Ou NodePort, dependendo de como você deseja expor
