apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80        # A porta externa (do host)
      targetPort: 80    # A porta interna do container
  type: ClusterIP   # Ou NodePort, dependendo de como você deseja expor
